/** Declaration file generated by dts-gen */
declare module "dorita980" {
export function Cloud(username: any, password: any, version: any): any;

export function Local(username: any, password: any, ip: any, version?: any, interval?: any): any;

export function discovery(cb: any): void;

export function getRobotIP(cb: any, full?: any): void;

export function getRobotPublicInfo(ip: any, cb: any): void;
}